workaround for #22
pymodbus-dev/repl pull request #23
Opened 2024-11-16 17:18 UTC by dhoomakethu

Fix pymodbus version to v3.7.0

2024-11-20 22:56 UTC, alexrudd2 approved these changes
LGTM as a temporary fix

2024-11-20 22:58 UTC, alexrudd2 requested changes

2024-11-20 22:58 UTC, alexrudd2 commented on pyproject.toml
> +pymodbus = {git = "https://github.com/pymodbus-dev/pymodbus", tag = "v3.7.0"}
I think the latest working version is actually `3.6.9` not `3.7.0`

2024-11-23 07:39 UTC, dhoomakethu commented on pyproject.toml
> +pymodbus = {git = "https://github.com/pymodbus-dev/pymodbus", tag = "v3.7.0"}
I checked with 3.7.0 and it was working.

2024-11-26 16:28 UTC, alexrudd2 approved these changes

2024-11-28 15:30 UTC, merged